<a href="https://colab.research.google.com/github/Bianchez00/ProgrammingAndDatabase/blob/main/Exam_04_02_2025.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Ex 1**: Write a function that takes a list of strings in input and returns a new list that contains every first character of each of the strings contained in the input list.

Do not use for or while loops for this.

Assume that the input is always a list of strings.

Example execution:

```python
ls = ['ab', 'cd', 'ef']
fun(ls)
```
> ['a', 'c', 'e']

In [ ]:
#your code here

**Ex 2**: Write a function that takes a list of integers as input and returns a list of all the odd integers if the input list contains at least one even integer. Otherwise, the function will return an empty list.

Assume that the input is always a list of integers.

Example execution:

```python
ls = [1, 2, 3, 4, 5, 6, 7]
fun(ls)
```
> [1, 3, 5, 7]

In [ ]:
#your code here

**Ex 3**: Write a function that takes a list of integers as input and outputs a list that contains all the odd numbers in the input list, multiplied by 2.

Assume that the input is always a list of integers.    

Example execution:

```python
ls = [1, 2, 3, 4, 5, 6]
fun(ls)
```
> [2, 6, 10]

In [ ]:
#your code here

**Ex 4**: Write the definition of an object “Supermarket” that describes a specific supermarket. The attributes of this object will be 1. Its name, 2. Its location and 3. Its size (an integer that represents square meters). It will take these 3 attributes as input for the initialization of the object instance.

Two instances of the object “Supermarket” should be equal if they have the same name and location.

Bonus: write a method that allows the user to increase the size of the supermarket by a set amount.

Example execution:

```python
obj_1 = Supermarket('Migross', 'Caprino', 500)
obj_2 = Supermarket('Migross', 'Caprino', 400)
print(obj_1 == obj_2)
```
> True

In [ ]:
#your code here

**Ex 5**: Write a function that takes a list of dictionaries as input and returns a list containing all the values from all the dictionaries, sorted in descending order.
If the input is not of the correct type (a list of dictionaries), then print the string “WRONG INPUT TYPE” and exit the function.

Example execution:

```python
ls = [{'a':1, 'b':2}, {'c':4}]
fun(ls)
```
> [4, 2, 1]

In [ ]:
#your code here

**Ex 6**: Write a function that takes two integers “a” and “b” as input, and generates a Numpy array of size aXb (rows X columns) that is formed by the numbers from 1 to a*b, in order (left to right).

The function will then change all the even values in the array to -1 and return the resulting array.

Example execution:

```python
a = 3
b = 2
fun(a,b)
```
> array([[ 1, -1],
       [ 3, -1],
       [ 5, -1]])

In [ ]:
#your code here

**Ex 7**: Write a function that takes a Numpy array of integers as input and returns a new array where every element of the even columns in the input array is substituted by the value -1.

You must check the input for correctness.

Example execution:

```python
arr = np.array([[1, 2, 3, 4],
        [5, 6, 7, 8],
        [9, 10, 11, 12],
        [13, 14, 15, 16]])
fun(arr)
```
> array([[-1,  2, -1,  4],
       [-1,  6, -1,  8],
       [-1, 10, -1, 12],
       [-1, 14, -1, 16]])

In [ ]:
#your code here

Ex 8: Write a function that takes a Numpy array of integers as input and returns a new array containing only the positive even integers.

Do not use for loops, if statements and list comprehensions.

Example execution:

```python
arr = np.array([-2, 3, 56, 12, -3])
fun(arr)
```
> array([56, 12])

In [ ]:
#your code here

Ex 9: Write a function that takes two Numpy arrays as input and returns their dot product. If any exception arises, print “AN EXCEPTION HAS ARISEN” and exit the function without showing the exception.

Do not check the input for correctness.


Example execution:
```python
arr = np.array([1,2,3,4])
fun(arr, arr)
```
> 30

In [ ]:
#your code here

**Ex 10**: Write a function that takes a Numpy array of integers as input and outputs the index of the row with the highest sum of elements.

You must check the input for correctness.


Example execution:
```python
arr = array([[ 0,  1,  2,  3],
                 [ 4,  5,  6,  7],
                 [ 8,  9, 10, 11],
                 [12, 13, 14, 15]])
fun(arr)
```
> 3

In [ ]:
#your code here

**Ex 11**: Take the two csv datasets and merge them into a unified DataFrame.

With this unified DataFrame, remove all the rows with null values and eventual redundant columns.


In [ ]:
#your code here

**Ex 12**: Use a lambda function to change all the column names of the DataFrame to lowercase strings where the spaces have been substituted by an underscore (“_”).

In [ ]:
#your code here

**Ex 13**: Perform the usual steps for Exploratory Data Analysis on the unified DataFrame and write what you think is interesting in a comment.

In [ ]:
#your code here

**Ex 14**: In the unified DataFrame, create a new column “name_surname” that contains the name and surname of the users. Remove the newly redundant columns.

In [ ]:
#your code here

**Ex 15**: Using pandas, find out which item has generated the most revenue (the amount of money it brought to the company). Bonus: using pandas, find which seller has sold the most of this Item.

In [ ]:
#your code here